version: '3.5'
services:
 web_dev:
  build: .
  ports:
   - "4000:4000"
  command: /usr/local/bin/gunicorn -w 2 -t 3600 -b :4000 index:app --reload
  volumes:
   - ./:/usr/src/app
  stdin_open: true
  tty: true
  environment:
   - ENV=development
   - PORT=4000
   - DB=mongodb://mongodb:27017/dev
   - SECRET='cashrules'
   - CLIENT_ID=client_id_sHtD45yjIkYubLAXaog2mqOPzN68lSFRCMcU731E
   - CLIENT_SECRET=client_secret_7wcdXC25xFa8lDsKjBhH1MGe4LyYTmuvgkVIzWO6
 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/usr/data/db
  ports:
   - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
 default:
  name: web_dev